/**
 * Standard error codes across all APIs
 * Enables client-side error handling and consistent responses
 */

export const ErrorCodes = {
  // Authentication & Authorization
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  AUTH_FAILED: 'AUTH_FAILED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_REQUEST: 'INVALID_REQUEST',
  MISSING_FIELD: 'MISSING_FIELD',
  INVALID_FORMAT: 'INVALID_FORMAT',

  // Resource Management
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RESOURCE_EXISTS: 'RESOURCE_EXISTS',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',

  // Rate Limiting & Abuse
  RATE_LIMITED: 'RATE_LIMITED',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

  // Financial Operations
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  TRANSACTION_FAILED: 'TRANSACTION_FAILED',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  DAILY_LIMIT_EXCEEDED: 'DAILY_LIMIT_EXCEEDED',

  // Fraud Detection
  FRAUD_DETECTED: 'FRAUD_DETECTED',
  SUSPICIOUS_ACTIVITY: 'SUSPICIOUS_ACTIVITY',
  HIGH_RISK: 'HIGH_RISK',

  // Wallet Operations
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  INVALID_ADDRESS: 'INVALID_ADDRESS',
  ADDRESS_MISMATCH: 'ADDRESS_MISMATCH',

  // External Services
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  RPC_ERROR: 'RPC_ERROR',
  API_ERROR: 'API_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  TIMEOUT: 'TIMEOUT',

  // Database & Server
  DATABASE_ERROR: 'DATABASE_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];

/**
 * HTTP status code mapping for error codes
 */
export const ErrorCodeToStatusMap: Record<ErrorCode, number> = {
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  AUTH_FAILED: 401,
  TOKEN_EXPIRED: 401,
  INVALID_TOKEN: 401,

  VALIDATION_ERROR: 400,
  INVALID_REQUEST: 400,
  MISSING_FIELD: 400,
  INVALID_FORMAT: 400,

  NOT_FOUND: 404,
  CONFLICT: 409,
  RESOURCE_EXISTS: 409,
  DUPLICATE_ENTRY: 409,

  RATE_LIMITED: 429,
  RATE_LIMIT_EXCEEDED: 429,
  TOO_MANY_REQUESTS: 429,

  INSUFFICIENT_BALANCE: 400,
  INSUFFICIENT_FUNDS: 400,
  TRANSACTION_FAILED: 400,
  INVALID_AMOUNT: 400,
  DAILY_LIMIT_EXCEEDED: 403,

  FRAUD_DETECTED: 403,
  SUSPICIOUS_ACTIVITY: 403,
  HIGH_RISK: 403,

  WALLET_NOT_FOUND: 404,
  INVALID_ADDRESS: 400,
  ADDRESS_MISMATCH: 400,

  EXTERNAL_SERVICE_ERROR: 502,
  RPC_ERROR: 502,
  API_ERROR: 502,
  NETWORK_ERROR: 503,
  TIMEOUT: 504,

  DATABASE_ERROR: 500,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
};

/**
 * Get HTTP status code for error code
 */
export function getStatusForErrorCode(code: ErrorCode): number {
  return ErrorCodeToStatusMap[code] || 500;
}
